version: "3.9"

services:
  postgres:
    image: postgres:9.6.24
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: always
  api:
    image: golang:1.18.2
    build:
      context: ./cmd/api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./data:/data
      - ./config:/config
      - ./logs:/logs